/* tslint:disable */
/* eslint-disable */
/**
 * Aftermeal API Docs
 * 에프터밀 API 엔드포인트(Endpoint)와 객체 정보, 파라미터, 요청 및 응답 예제를 살펴보세요.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ActivityScheduleListResponse
 */
export interface ActivityScheduleListResponse {
    /**
     * 
     * @type {number}
     * @memberof ActivityScheduleListResponse
     */
    'activityScheduleId'?: number;
    /**
     * 
     * @type {string}
     * @memberof ActivityScheduleListResponse
     */
    'name'?: string;
    /**
     * 
     * @type {number}
     * @memberof ActivityScheduleListResponse
     */
    'maxParticipants'?: number;
    /**
     * 
     * @type {number}
     * @memberof ActivityScheduleListResponse
     */
    'currentParticipants'?: number;
    /**
     * 
     * @type {string}
     * @memberof ActivityScheduleListResponse
     */
    'status'?: ActivityScheduleListResponseStatus;
    /**
     * 
     * @type {string}
     * @memberof ActivityScheduleListResponse
     */
    'type'?: ActivityScheduleListResponseType;
    /**
     * 
     * @type {string}
     * @memberof ActivityScheduleListResponse
     */
    'scheduledDate'?: string;
}

export const ActivityScheduleListResponseStatus = {
    Scheduled: 'SCHEDULED',
    InProgress: 'IN_PROGRESS',
    Canceled: 'CANCELED',
    Completed: 'COMPLETED'
} as const;

export type ActivityScheduleListResponseStatus = typeof ActivityScheduleListResponseStatus[keyof typeof ActivityScheduleListResponseStatus];
export const ActivityScheduleListResponseType = {
    Lunch: 'LUNCH',
    Dinner: 'DINNER'
} as const;

export type ActivityScheduleListResponseType = typeof ActivityScheduleListResponseType[keyof typeof ActivityScheduleListResponseType];


