/* tslint:disable */
/* eslint-disable */
/**
 * Aftermeal API Docs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserRegistrationRequestDto
 */
export interface UserRegistrationRequestDto {
    /**
     * 
     * @type {string}
     * @memberof UserRegistrationRequestDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof UserRegistrationRequestDto
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof UserRegistrationRequestDto
     */
    'userType': UserRegistrationRequestDtoUserType;
    /**
     * 
     * @type {number}
     * @memberof UserRegistrationRequestDto
     */
    'generationNumber'?: number;
    /**
     * 
     * @type {string}
     * @memberof UserRegistrationRequestDto
     */
    'password': string;
}

export const UserRegistrationRequestDtoUserType = {
    Student: 'STUDENT',
    Teacher: 'TEACHER'
} as const;

export type UserRegistrationRequestDtoUserType = typeof UserRegistrationRequestDtoUserType[keyof typeof UserRegistrationRequestDtoUserType];


