/* tslint:disable */
/* eslint-disable */
/**
 * Aftermeal API Docs
 * 에프터밀 API 엔드포인트(Endpoint)와 객체 정보, 파라미터, 요청 및 응답 예제를 살펴보세요.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserUpdateRequest
 */
export interface UserUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof UserUpdateRequest
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateRequest
     */
    'type'?: UserUpdateRequestType;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateRequest
     */
    'status'?: UserUpdateRequestStatus;
    /**
     * 
     * @type {number}
     * @memberof UserUpdateRequest
     */
    'generationNumber'?: number;
}

export const UserUpdateRequestType = {
    Student: 'STUDENT',
    Teacher: 'TEACHER'
} as const;

export type UserUpdateRequestType = typeof UserUpdateRequestType[keyof typeof UserUpdateRequestType];
export const UserUpdateRequestStatus = {
    Activate: 'ACTIVATE',
    Deactivate: 'DEACTIVATE'
} as const;

export type UserUpdateRequestStatus = typeof UserUpdateRequestStatus[keyof typeof UserUpdateRequestStatus];


