/* tslint:disable */
/* eslint-disable */
/**
 * AfterMeal API Docs
 * 에프터밀 API 엔드포인트(Endpoint)와 객체 정보, 파라미터, 요청 및 응답 예제를 살펴보세요.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface LoginResponseDtoUser
 */
export interface LoginResponseDtoUser {
  /**
   *
   * @type {string}
   * @memberof LoginResponseDtoUser
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof LoginResponseDtoUser
   */
  name: string;
  /**
   *
   * @type {Array<string>}
   * @memberof LoginResponseDtoUser
   */
  roles: Array<LoginResponseDtoUserRoles>;
}

export const LoginResponseDtoUserRoles = {
  User: 'USER',
  Admin: 'ADMIN',
} as const;

export type LoginResponseDtoUserRoles =
  (typeof LoginResponseDtoUserRoles)[keyof typeof LoginResponseDtoUserRoles];
