/* tslint:disable */
/* eslint-disable */
/**
 * Aftermeal API Docs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TokenRefreshResponseDto
 */
export interface TokenRefreshResponseDto {
    /**
     * 
     * @type {string}
     * @memberof TokenRefreshResponseDto
     */
    'accessToken': string;
    /**
     * 
     * @type {string}
     * @memberof TokenRefreshResponseDto
     */
    'tokenType': string;
    /**
     * 
     * @type {number}
     * @memberof TokenRefreshResponseDto
     */
    'expiredIn': number;
    /**
     * 
     * @type {string}
     * @memberof TokenRefreshResponseDto
     */
    'refreshToken': string;
}

