/* tslint:disable */
/* eslint-disable */
/**
 * Aftermeal API Docs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ActivityScheduleStatusUpdateDto
 */
export interface ActivityScheduleStatusUpdateDto {
    /**
     * 
     * @type {string}
     * @memberof ActivityScheduleStatusUpdateDto
     */
    'status': ActivityScheduleStatusUpdateDtoStatus;
}

export const ActivityScheduleStatusUpdateDtoStatus = {
    Scheduled: 'SCHEDULED',
    InProgress: 'IN_PROGRESS',
    Canceled: 'CANCELED',
    Completed: 'COMPLETED'
} as const;

export type ActivityScheduleStatusUpdateDtoStatus = typeof ActivityScheduleStatusUpdateDtoStatus[keyof typeof ActivityScheduleStatusUpdateDtoStatus];


