/* tslint:disable */
/* eslint-disable */
/**
 * AfterMeal API Docs
 * 에프터밀 API 엔드포인트(Endpoint)와 객체 정보, 파라미터, 요청 및 응답 예제를 살펴보세요.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ActivityScheduleUpdateDto
 */
export interface ActivityScheduleUpdateDto {
    /**
     * 
     * @type {string}
     * @memberof ActivityScheduleUpdateDto
     */
    'title'?: string;
    /**
     * 
     * @type {number}
     * @memberof ActivityScheduleUpdateDto
     */
    'maxParticipants'?: number;
    /**
     * 
     * @type {string}
     * @memberof ActivityScheduleUpdateDto
     */
    'status'?: ActivityScheduleUpdateDtoStatus;
    /**
     * 
     * @type {string}
     * @memberof ActivityScheduleUpdateDto
     */
    'type'?: ActivityScheduleUpdateDtoType;
    /**
     * 
     * @type {string}
     * @memberof ActivityScheduleUpdateDto
     */
    'scheduledDate'?: string;
}

export const ActivityScheduleUpdateDtoStatus = {
    Scheduled: 'SCHEDULED',
    InProgress: 'IN_PROGRESS',
    Canceled: 'CANCELED',
    Completed: 'COMPLETED'
} as const;

export type ActivityScheduleUpdateDtoStatus = typeof ActivityScheduleUpdateDtoStatus[keyof typeof ActivityScheduleUpdateDtoStatus];
export const ActivityScheduleUpdateDtoType = {
    Lunch: 'LUNCH',
    Dinner: 'DINNER'
} as const;

export type ActivityScheduleUpdateDtoType = typeof ActivityScheduleUpdateDtoType[keyof typeof ActivityScheduleUpdateDtoType];


