/* tslint:disable */
/* eslint-disable */
/**
 * AfterMeal API Admin Docs
 * 에프터밀 관리자 API 엔드포인트(Endpoint)와 객체 정보, 파라미터, 요청 및 응답 예제를 살펴보세요.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ActivityUpdateRequestDto
 */
export interface ActivityUpdateRequestDto {
  /**
   *
   * @type {string}
   * @memberof ActivityUpdateRequestDto
   */
  title?: string;
  /**
   *
   * @type {number}
   * @memberof ActivityUpdateRequestDto
   */
  maxParticipants?: number;
  /**
   *
   * @type {string}
   * @memberof ActivityUpdateRequestDto
   */
  location?: string;
  /**
   *
   * @type {string}
   * @memberof ActivityUpdateRequestDto
   */
  status?: ActivityUpdateRequestDtoStatus;
  /**
   *
   * @type {string}
   * @memberof ActivityUpdateRequestDto
   */
  type?: ActivityUpdateRequestDtoType;
  /**
   *
   * @type {string}
   * @memberof ActivityUpdateRequestDto
   */
  scheduledDate?: string;
  /**
   *
   * @type {string}
   * @memberof ActivityUpdateRequestDto
   */
  applicationStartAt?: string;
  /**
   *
   * @type {string}
   * @memberof ActivityUpdateRequestDto
   */
  applicationEndAt?: string;
}

export const ActivityUpdateRequestDtoStatus = {
  Scheduled: 'SCHEDULED',
  InProgress: 'IN_PROGRESS',
  Canceled: 'CANCELED',
  Completed: 'COMPLETED',
} as const;

export type ActivityUpdateRequestDtoStatus =
  (typeof ActivityUpdateRequestDtoStatus)[keyof typeof ActivityUpdateRequestDtoStatus];
export const ActivityUpdateRequestDtoType = {
  Lunch: 'LUNCH',
  Dinner: 'DINNER',
} as const;

export type ActivityUpdateRequestDtoType =
  (typeof ActivityUpdateRequestDtoType)[keyof typeof ActivityUpdateRequestDtoType];
