/* tslint:disable */
/* eslint-disable */
/**
 * AfterMeal API Docs
 * 에프터밀 API 엔드포인트(Endpoint)와 객체 정보, 파라미터, 요청 및 응답 예제를 살펴보세요.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserRegistrationRequestDto
 */
export interface UserRegistrationRequestDto {
    /**
     * 
     * @type {string}
     * @memberof UserRegistrationRequestDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof UserRegistrationRequestDto
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof UserRegistrationRequestDto
     */
    'type': UserRegistrationRequestDtoType;
    /**
     * 
     * @type {number}
     * @memberof UserRegistrationRequestDto
     */
    'generationNumber'?: number;
    /**
     * 
     * @type {string}
     * @memberof UserRegistrationRequestDto
     */
    'password': string;
}

export const UserRegistrationRequestDtoType = {
    Student: 'STUDENT',
    Teacher: 'TEACHER'
} as const;

export type UserRegistrationRequestDtoType = typeof UserRegistrationRequestDtoType[keyof typeof UserRegistrationRequestDtoType];


