/* tslint:disable */
/* eslint-disable */
/**
 * AfterMeal API Admin Docs
 * 에프터밀 관리자 API 엔드포인트(Endpoint)와 객체 정보, 파라미터, 요청 및 응답 예제를 살펴보세요. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserUpdateRequestDto
 */
export interface UserUpdateRequestDto {
    /**
     * 
     * @type {string}
     * @memberof UserUpdateRequestDto
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateRequestDto
     */
    'type'?: UserUpdateRequestDtoType;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateRequestDto
     */
    'status'?: UserUpdateRequestDtoStatus;
    /**
     * 
     * @type {number}
     * @memberof UserUpdateRequestDto
     */
    'generationNumber'?: number;
}

export const UserUpdateRequestDtoType = {
    Student: 'STUDENT',
    Teacher: 'TEACHER'
} as const;

export type UserUpdateRequestDtoType = typeof UserUpdateRequestDtoType[keyof typeof UserUpdateRequestDtoType];
export const UserUpdateRequestDtoStatus = {
    Activate: 'ACTIVATE',
    Deactivate: 'DEACTIVATE'
} as const;

export type UserUpdateRequestDtoStatus = typeof UserUpdateRequestDtoStatus[keyof typeof UserUpdateRequestDtoStatus];


